spring.application.name=Product_Management-API

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.password=sadiqqidas777
spring.datasource.username=postgres

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.root = debug
#
#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=update

spring.liquibase.change-log=classpath:liquibase/changelog-master.yaml
spring.liquibase.enabled=true

#springdoc.swagger-ui.path=/swagger-ui/swagger-ui/index.html