spring.application.name=Product_Management-API

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=product_schema
spring.datasource.password=sadiqqidas777
spring.datasource.username=postgres

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=update
